      SUBROUTINE TRAP(A,B,N,INTEGRAL)
      !CALCULATE INTEGRAL OF FUNCTION WITH EVEN INTERVAL
      IMPLICIT NONE
      REAL(kind=8)  :: A,B,F,H,INTEGRAL,X
      INTEGER :: N,I
      F(X) = 4.0d0/(1.d0+X**2)        !FUNCTION DEFINITION
      H(A,B,N) = (B-A)/REAL(N)    !INTERVAL DEFINITION
      INTEGRAL = 0.5d0*(F(A)+F(B))!INITIALIZE INTEGRAL
      DO I = 1,N-1
         X = A + REAL(I)*H(A,B,N)
         INTEGRAL = INTEGRAL + F(X)
      END DO
      INTEGRAL = H(A,B,N)*INTEGRAL
      RETURN
      END
